version: '3.8'
services:
  postgres:
    image: postgres:10
    ports:
      - 5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  app:
    build: .
    ports:
      - 9999:9999
      - 8080:8080
    depends_on:
      - postgres
    command: yarn start:backend:docker
