# https://circleci.com/docs/2.0/language-javascript/
version: 2
jobs:
  'node-12':
    docker:
      - image: circleci/node:12
      - image: circleci/postgres:12.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: yavin_test
          POSTGRES_HOST_AUTH_METHOD: trust # passwordless
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "frontend/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - run: cd frontend && yarn install
      - save_cache:
          paths:
            - node_modules
            - frontend/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "frontend/package.json" }}
      - run: yarn test
      - store_test_results:
          path: coverage

workflows:
  version: 2
  build:
    jobs:
      - 'node-12'
